context:
  name: pydiverse-colspec
  version: "0.2.1"
  python_min: '3.11'

package:
  name: pydiverse-colspec
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/${{ name }}/${{ name | replace("-", "_") }}-${{ version }}.tar.gz
    sha256: aa7b73175fcfc6236e88cbb3a91a72efbfc8220e00a7c15b7a610dc4ec76b8d2

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - pydiverse-common >=0.3.4,<0.4
    - structlog >=25.4.0,<26
  run_constraints:
    - pydiverse-transform >=0.5.0,<0.6
    - pydiverse-pipedag >=0.10.0,<0.11
    - pyarrow >=20.0.0,<21
    - dataframely >=1.1.0,<2

tests:
  - python:
      imports:
        - pydiverse.colspec
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Validate column specifications and constraints for SQL tables and polars data frames.
  description: |
    A data validation library that ensures type conformity of columns in SQL tables and polars data frames.
    It can also validate constraints regarding the data as defined in a so-called column specification provided by the user.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pydiverse/pydiverse.colspec
  repository: https://github.com/pydiverse/pydiverse.colspec
  documentation: https://pydiversecolspec.readthedocs.io

extra:
  recipe-maintainers:
    - pavelzw
    - windiana42
